name: Comment when opened
on:
    pull_request:
      types: [opened, reopened, synchronize, ready_for_review]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Enable Pull Request Automerge
        if: ${{ github.event.pull_request.draft == false }}
        run: gh pr merge "${{ github.event.pull_request.number }}" --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
