name: Comment when opened
on:
    pull_request:
      types: [opened, reopened, synchronize]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge "${{ github.event.pull_request.number }}" --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
