name: Enable Auto-Merge for PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enable_auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
          gh pr merge ${{ github.event.pull_request.number }} --auto
