name: Comment when opened
on:
    pull_request:
      types: [opened, reopened, synchronize]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        

