# yamllint disable rule:line-length
---
  name: Print Formatted Username
  on: [push]
  jobs:
    print-username:
      runs-on: ubuntu-latest
      name: Print Formatted Username
      steps:
        - name: Extract and format username
          id: extract
          uses: actions/github-script@v7
          with:
            script: |
              const actor = '${{ github.actor }}';
              const regex = /(\w+)-(\w+)-(\w+)/;
              const matches = actor.match(regex);
              console.log(matches);
              if (matches) {
                const formattedUsername = `@${matches[1]} ${matches[2]}`;
                return { formattedUsername };
              } else {
                console.log("in the else");
                return { formattedUsername: '' };
              }
        - name: Print formatted username
          run: echo "${{ steps.extract.outputs.result.formattedUsername }}" 